@echo off
echo Limpando processos Node.js...
taskkill /F /IM node.exe >nul 2>&1

echo Aguardando processos fecharem...
timeout /t 2 /nobreak >nul

echo Removendo cache .next...
if exist .next rmdir /s /q .next

echo Iniciando servidor...
npm run dev
