import type { BusinessSegment, SegmentQuestion } from '@/types/config.types'

export const SEGMENT_LABELS: Record<BusinessSegment, string> = {
  restaurante: 'Restaurante',
  clinica: 'Clínica Médica',
  barbearia: 'Barbearia',
  salao_beleza: 'Salão de Beleza',
  consultorio: 'Consultório',
  outro: 'Outro',
}

export const SEGMENT_QUESTIONS: Record<BusinessSegment, SegmentQuestion[]> = {
  restaurante: [
    {
      id: 'cuisineType',
      label: 'Tipo de Culinária',
      type: 'select',
      options: [
        'Italiana',
        'Brasileira',
        'Japonesa',
        'Árabe',
        'Francesa',
        'Mexicana',
        'Contemporânea',
        'Fast Food',
        'Churrascaria',
        'Frutos do Mar',
        'Vegetariana/Vegana',
        'Outro',
      ],
      required: true,
    },
    {
      id: 'acceptsReservations',
      label: 'Aceita reservas antecipadas?',
      type: 'checkbox',
      required: false,
    },
    {
      id: 'averageServiceTime',
      label: 'Tempo médio de atendimento (minutos)',
      type: 'number',
      placeholder: '45',
      required: true,
    },
    {
      id: 'seatingCapacity',
      label: 'Capacidade de lugares',
      type: 'number',
      placeholder: '50',
      required: false,
    },
  ],
  clinica: [
    {
      id: 'specialties',
      label: 'Especialidades Médicas',
      type: 'multiselect',
      options: [
        'Cardiologia',
        'Ortopedia',
        'Pediatria',
        'Ginecologia',
        'Dermatologia',
        'Oftalmologia',
        'Neurologia',
        'Psiquiatria',
        'Clínica Geral',
        'Otorrinolaringologia',
        'Urologia',
        'Endocrinologia',
      ],
      required: true,
    },
    {
      id: 'acceptsInsurance',
      label: 'Aceita planos de saúde?',
      type: 'checkbox',
      required: false,
    },
    {
      id: 'insuranceProviders',
      label: 'Quais planos de saúde? (separados por vírgula)',
      type: 'text',
      placeholder: 'Unimed, Bradesco Saúde, SulAmérica',
      required: false,
    },
    {
      id: 'averageServiceTime',
      label: 'Tempo médio de consulta (minutos)',
      type: 'number',
      placeholder: '30',
      required: true,
    },
  ],
  barbearia: [
    {
      id: 'services',
      label: 'Serviços Oferecidos',
      type: 'multiselect',
      options: [
        'Corte de Cabelo',
        'Corte de Barba',
        'Combo (Cabelo + Barba)',
        'Coloração',
        'Tratamento Capilar',
        'Sobrancelha',
        'Platinado',
        'Luzes',
        'Depilação',
      ],
      required: true,
    },
    {
      id: 'acceptsScheduling',
      label: 'Aceita agendamento prévio?',
      type: 'checkbox',
      required: false,
    },
    {
      id: 'averageServiceTime',
      label: 'Tempo médio de atendimento (minutos)',
      type: 'number',
      placeholder: '30',
      required: true,
    },
    {
      id: 'numberOfChairs',
      label: 'Número de cadeiras',
      type: 'number',
      placeholder: '3',
      required: false,
    },
  ],
  salao_beleza: [
    {
      id: 'services',
      label: 'Serviços Oferecidos',
      type: 'multiselect',
      options: [
        'Corte Feminino',
        'Corte Masculino',
        'Coloração',
        'Mechas/Luzes',
        'Escova',
        'Hidratação',
        'Progressiva',
        'Botox Capilar',
        'Manicure',
        'Pedicure',
        'Design de Sobrancelhas',
        'Depilação',
        'Maquiagem',
      ],
      required: true,
    },
    {
      id: 'acceptsScheduling',
      label: 'Aceita agendamento prévio?',
      type: 'checkbox',
      required: false,
    },
    {
      id: 'averageServiceTime',
      label: 'Tempo médio de atendimento (minutos)',
      type: 'number',
      placeholder: '60',
      required: true,
    },
    {
      id: 'numberOfStations',
      label: 'Número de estações de trabalho',
      type: 'number',
      placeholder: '5',
      required: false,
    },
  ],
  consultorio: [
    {
      id: 'specialties',
      label: 'Especialidades',
      type: 'multiselect',
      options: [
        'Psicologia',
        'Nutrição',
        'Fisioterapia',
        'Fonoaudiologia',
        'Terapia Ocupacional',
        'Psicopedagogia',
        'Odontologia',
        'Acupuntura',
        'Quiropraxia',
        'Coaching',
      ],
      required: true,
    },
    {
      id: 'acceptsInsurance',
      label: 'Aceita planos de saúde?',
      type: 'checkbox',
      required: false,
    },
    {
      id: 'insuranceProviders',
      label: 'Quais planos? (separados por vírgula)',
      type: 'text',
      placeholder: 'Unimed, Bradesco, SulAmérica',
      required: false,
    },
    {
      id: 'averageServiceTime',
      label: 'Tempo médio de sessão (minutos)',
      type: 'number',
      placeholder: '50',
      required: true,
    },
    {
      id: 'sessionType',
      label: 'Tipo de sessão padrão',
      type: 'select',
      options: ['Individual', 'Casal', 'Grupo', 'Familiar'],
      required: false,
    },
  ],
  outro: [
    {
      id: 'description',
      label: 'Descreva seu tipo de negócio',
      type: 'text',
      placeholder: 'Ex: Pet shop, academia, escola de idiomas...',
      required: true,
    },
    {
      id: 'serviceType',
      label: 'Tipo de serviço prestado',
      type: 'text',
      placeholder: 'Ex: Atendimento individual, aulas em grupo...',
      required: false,
    },
    {
      id: 'averageServiceTime',
      label: 'Tempo médio de atendimento (minutos)',
      type: 'number',
      placeholder: '30',
      required: true,
    },
    {
      id: 'acceptsScheduling',
      label: 'Trabalha com agendamento?',
      type: 'checkbox',
      required: false,
    },
  ],
}
